export const listofPatients = [
  {
    avatar: './source/img/patient-avatar.png',
    firstName: 'Ronnie',
    lastName: 'Wood',
    status: 'Appointment is confirmed',
    description: 'We will invite you in for a full review every year and more frequently if you are struggling with blood sugar levels.',
    time: 'Thu Sept 10, 2021 4 pm – 5 pm',
    id: '1',
  },
  {
    avatar: './source/img/patient-avatar.png',
    firstName: 'Ronnie',
    lastName: 'Wood',
    status: 'Appointment is confirmed',
    description: 'We will invite you in for a full review every year and more frequently if you are struggling with blood sugar levels.',
    time: 'Thu Sept 10, 2021 4 pm – 5 pm',
    id: '2',
  },
  {
    avatar: './source/img/patient-avatar.png',
    firstName: 'Ronnie',
    lastName: 'Wood',
    status: 'Appointment is confirmed',
    description: 'We will invite you in for a full review every year and more frequently if you are struggling with blood sugar levels.',
    time: 'Thu Sept 10, 2021 4 pm – 5 pm',
    id: '3',
  },
  {
    avatar: './source/img/patient-avatar.png',
    firstName: 'Ronnie',
    lastName: 'Wood',
    status: 'Appointment is confirmed',
    description: 'We will invite you in for a full review every year and more frequently if you are struggling with blood sugar levels.',
    time: 'Thu Sept 10, 2021 4 pm – 5 pm',
    id: '4',
  },
  {
    avatar: './source/img/patient-avatar.png',
    firstName: 'Ronnie',
    lastName: 'Wood',
    status: 'Appointment is confirmed',
    description: 'We will invite you in for a full review every year and more frequently if you are struggling with blood sugar levels.',
    time: 'Thu Sept 10, 2021 4 pm – 5 pm',
    id: '5',
  },
];
